### ISSUE TITLE
TypeError: Cannot read property 'afterEmit' of undefined

### ISSUE THREAD

**Issue by rickmacgillis** [MikaAK/s3-plugin-webpack#105]
I'm not a node dev; I'm a PHP dev. So, I have no idea what to do to fix this issue. When I compile the JS without this plugin, everything works smoothly.

For the longest time, everything worked well with the plugin. However, even when I reverted all of my code from working on the JS today, I still couldn't get it to compile properly with this plugin.

Just an FYI, I'm using Laravel Mix to compile everything. Perhaps it's a cache issue, but I tried clearing the caches I knew about, deleting the node_modules directory, reverting my package.json, and reverting my webpack.mix.js file. I'm at a loss as to what could possibly be causing this issue.

Here's the call stack from `npm run prod` using Laravel Mix.

```
TypeError: Cannot read property 'afterEmit' of undefined
    at t.exports.apply (/var/www/[REDACTED]/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:3230)
    at Compiler.apply (/var/www/[REDACTED]/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/var/www/[REDACTED]/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/var/www/[REDACTED]/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/var/www/[REDACTED]/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/var/www/[REDACTED]/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/var/www/[REDACTED]/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```
If you need more info to help me troubleshoot it, please let me know what info you need.

**Comment by MikaAK** [comment]
update webpack or use v1.0.0-rc

**Comment by rickmacgillis** [comment]
I'm already using 1.0.0-rc. Here's my package.json.

```
{
   "private": true,
   "scripts": {
      "dev": "npm run development",
      "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch": "npm run development -- --watch",
      "watch-poll": "npm run watch -- --watch-poll",
      "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
      "prod": "npm run production",
      "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
   },
   "devDependencies": {
      "axios": "^0.18",
      "bootstrap": "^4.1.3",
      "cross-env": "^5.1",
      "jquery": "^3.2",
      "js-cookie": "^2.1.0",
      "laravel-echo": "^1.4.0",
      "laravel-mix": "^2.0",
      "less": "^2.7.3",
      "less-loader": "^4.1.0",
      "lodash": "^4.17.10",
      "moment": "^2.22.2",
      "popper.js": "^1.14.4",
      "promise": "^7.1.1",
      "pusher-js": "^4.3.0",
      "sweetalert": "^1.1.3",
      "tokenfield": "^0.9.10",
      "urijs": "^1.19.1",
      "vue": "^2.5.17",
      "webpack": "^3.12.0",
      "webpack-s3-plugin": "^1.0.0-rc.0"
   }
}
```

**Comment by rickmacgillis** [comment]
Just a heads up, I couldn't update to Webpack 4 as Laravel Mix is incompatible with it at the time of writing.

SOLUTION: I fixed it by downgrading S3 Plugin to 0.9.2. Presumably the reason why it worked is that S3 Plugin 1.x is only able to work with Webpack 4.

**Comment by MikaAK** [comment]
Good to know, I may draft a release for everyone below WP 4

**Comment by SendDerek** [comment]
Thanks so much for posting the solution here.  I'm in the exact same situation, using Laravel 5.6 with Laravel Mix.  It was easy to change package.json to use '^0.9.2' and run `npm update webpack-s3-plugin`.  I'm gladly on my way again!
