### ISSUE TITLE
afterEmit of undefined - cause webpack compiler failure

### ISSUE THREAD

**Issue by idanhen** [MikaAK/s3-plugin-webpack#107]
**node version**; v8.11.4 ( also tested with v6.14.4 )
**s3-plugin-webpack:** 1.0.0/1.0.1/1.0.2 ( 1.0.0-rc.0 works ! )
**OS**: linux ubuntu 16.04

**Exception** : 
Creating an optimized production build...
Failed to compile.
 TypeError: Cannot read property 'afterEmit' of undefined
    at t.exports.apply (/home/user/Workspace/project/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:3230)
    at Compiler.apply (/home/user/Workspace/project/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/home/user/Workspace/project/node_modules/webpack/lib/webpack.js:33:19)
    at build (/home/user/Workspace/project/scripts/build.js:134:18)
    at measureFileSizesBeforeBuild.then.previousFileSizes (/home/user/Workspace/project/scripts/build.js:80:12)
    at <anonymous>
Cannot read property 'afterEmit' of undefined

If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

**Comment by MikaAK** [comment]
Next time search the issues
