### ISSUE TITLE
cdnizerOptions error

### ISSUE THREAD

**Issue by westn** [MikaAK/s3-plugin-webpack#3]
I've been trying to use this with both the the options on this page and with the following:
```
new S3Plugin({
  // s3Options are required
  s3Options: {
    accessKeyId: 'ACCESSKEY',
    secretAccessKey: 'secretAccessKey',
  },
  s3UploadOptions: {
    Bucket: 'myBucket',
    ACL: 'public-read'
  }
})
```

In both cases I get an error 

```
    if (!this.cdnizerOptions.files) this.cdnizerOptions.files = [];
                            ^
TypeError: Cannot read property 'files' of undefined
    at new S3Plugin (c:\Users\Fredrik\Documents\LBC\react\twitch-visualizer\node
_modules\webpack-s3-plugin\dist\s3_plugin.js:96:29)
    at Object.<anonymous> (c:\Users\Fredrik\Documents\LBC\react\twitch-visualize
r\webpack-production.config.js:30:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (c:\Users\Fredrik\Documents\LBC\react\twitch-visualizer\no
de_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (c:\Users\Fredrik\Documents\LBC\react\twitch-visualize
r\node_modules\webpack\bin\webpack.js:54:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

npm ERR! Twitch-Visualizer@1.0.0 prod: `webpack -p --config webpack-production.c
onfig.js --progress --colors`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the Twitch-Visualizer@1.0.0 prod script.
npm ERR! This is most likely a problem with the Twitch-Visualizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p --config webpack-production.config.js --progress --color
s
npm ERR! You can get their info via:
npm ERR!     npm owner ls Twitch-Visualizer
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
npm ERR! cwd c:\Users\Fredrik\Documents\LBC\react\twitch-visualizer
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\Fredrik\Documents\LBC\react\twitch-visualizer\npm-debug.lo
g
npm ERR! not ok code 0
```

**Comment by MikaAK** [comment]
Thanks for the report, try `v0.4.8` I've made a fix that should work!

**Comment by westn** [comment]
I still have an issue with the version, you have

```
this.cdnizerOptions.files.push('*' + fileName + '*');
```

which I think should be 
```
if(this.cdnizerOptions.files) this.cdnizerOptions.files.push('*' + fileName + '*');
```

**Comment by MikaAK** [comment]
Try `0.4.10`

**Comment by westn** [comment]
This part is working now, thanks!
