### ISSUE TITLE
Error: Cannot find module './helpers'

### ISSUE THREAD

**Issue by mattywong** [MikaAK/s3-plugin-webpack#33]
Getting this error whenever I put the require path in a webpack config.

Running Windows 8

`Error: Cannot find module './helpers'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Repositories\Clients\VolunteerLegacy\webhost\VolunteerWidgetv3\node_modules\webpack-s3-plugin\dist\s3_plugin.js:110:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Repositories\Clients\VolunteerLegacy\webhost\VolunteerWidgetv3\webpack.deploy.config.js:8:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)`

Where line 8 is 'var S3Plugin = require('webpack-s3-plugin');

**Comment by aris-b** [comment]
same here, after updating to the latest version.

**Comment by MikaAK** [comment]
Sorry about that I forgot about how modules bundle within gulp. I switched over to webpack so try `0.7.1`
